const express = require("express")
const { MongoClient } = require('mongodb');
const mongoose = require("mongoose")
const fs = require('fs'); // Fixed import
const app = express()

const myMiddleWare = (req, res, next) => {
    const date = new Date();
    fs.appendFile("./log.txt", `name : ${req.body.name}\n rollNo : ${req.body.rollNo}\n email : ${req.body.email}\n password : ${req.body.password}\n`, (err) => {
        if (err) {
            console.error(err);
        }
    });
    next(); // Call next() to proceed to the next middleware or route handler
};

const port = 5555

// call middleware
app.use(myMiddleWare);
app.use(express.json());  

const url = 'mongodb://localhost:27017/ExpressDB';

mongoose.connect(url)

.then(() => {
    console.log("Connect ot DB")
})

const userSchema = new mongoose.Schema({
    name:String,
    rollNo:Number,
    email:String,
    password:String
})

const userModel = mongoose.model("users" , userSchema)

app.post("/users" ,(req,res) => {
    const  users = new userModel
    ({
        name: req.body.name,
        rollNo: req.body.rollNo,
        eamil: req.body.email,
        password: req.body.password
    })
    users
        .save()
        .then(async() => {
            console.log("User Added");
            res.send("User Adde")

             // Generated by MongoDB Compass
            
            const filter = {};
            const client = await MongoClient.connect(
            'mongodb://localhost:27017/'
            );
            const coll = client.db('ExpressDB').collection('ExpressColl');
            const cursor = coll.find(filter);
            const result = await cursor.toArray();
            await client.close();

            res.json(result);
        })
        .catch(() => {console.log("error");
    })

})

// final listen
app.listen(port , () => {
    console.log("My port is running");
})